### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'save_to_log'

### ISSUE THREAD

**Issue by liaozhihao2757** [huixiancheng/SENet#11] opened 2022-10-26 15:44 UTC
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    trainer.train()
  File "/home/buaa/project_liaozhihao/CENet-main/modules/trainer.py", line 336, in train
    Trainer.save_to_log(logdir=self
AttributeError: type object 'Trainer' has no attribute 'save_to_log'

I found this issue when the code is training and this “Trainer.save_to_log” is not found in the Class Trainer.

**Comment by huixiancheng** [comment] 2022-10-27 04:13
Sorry for missing this part. Maybe fixed by upload this part. Welcome try again.

**Comment by liaozhihao2757** [comment] 2022-10-27 04:32
Is this related to the pytorch version, I am using the pytorch 1.9 and cuda 11.3

**Comment by huixiancheng** [comment] 2022-10-27 04:41
No. It just caused by code missing.

**Comment by huixiancheng** [comment] 2022-10-27 04:48
However, if y don't use tensorboard or save scan in valid, this part is useless.

**Comment by liaozhihao2757** [comment] 2022-10-27 04:56
okk, thank you very much.

**Closed as completed** 2022-10-27 06:50 UTC
